export const gradeData = [
  {
    gradeName: "Grade 1",
    twoPlusGradeBelow: 80,
    oneGradeBelow: 30,
    onGradeLevel: 40,
    aboveGradeLevel: 50,
  },
  {
    gradeName: "Grade 2",
    twoPlusGradeBelow: 20,
    oneGradeBelow: 30,
    onGradeLevel: 40,
    aboveGradeLevel: 50,
  },
  {
    gradeName: "Grade 3",
    twoPlusGradeBelow: 10,
    oneGradeBelow: 70,
    onGradeLevel: 80,
    aboveGradeLevel: 60,
  },
  {
    gradeName: "Grade 4",
    twoPlusGradeBelow: 5,
    oneGradeBelow: 30,
    onGradeLevel: 40,
    aboveGradeLevel: 60,
  },
  {
    gradeName: "Grade 5",
    twoPlusGradeBelow: 20,
    oneGradeBelow: 30,
    onGradeLevel: 25,
    aboveGradeLevel: 50,
  },
  {
    gradeName: "Grade 6",
    twoPlusGradeBelow: 20,
    oneGradeBelow: 30,
    onGradeLevel: 40,
    aboveGradeLevel: 50,
  },
  {
    gradeName: "Grade 7",
    twoPlusGradeBelow: 20,
    oneGradeBelow: 30,
    onGradeLevel: 40,
    aboveGradeLevel: 50,
  },
  {
    gradeName: "Grade 8",
    twoPlusGradeBelow: 20,
    oneGradeBelow: 30,
    onGradeLevel: 40,
    aboveGradeLevel: 50,
  },
  {
    gradeName: "Grade 9",
    twoPlusGradeBelow: 20,
    oneGradeBelow: 30,
    onGradeLevel: 40,
    aboveGradeLevel: 50,
  },
  {
    gradeName: "Grade 10",
    twoPlusGradeBelow: 0,
    oneGradeBelow: 30,
    onGradeLevel: 40,
    aboveGradeLevel: 50,
  },
  {
    gradeName: "Grade 11",
    twoPlusGradeBelow: 2,
    oneGradeBelow: 30,
    onGradeLevel: 40,
    aboveGradeLevel: 50,
  },
];
